CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Controllers/NhaXuatBanController.cs
using CuaHangSachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSachOnline.Areas.PageManagement.Controllers
{
    public class NhaXuatBanController : Controller
    {
        // GET: PageManagement/NhaXuatBan
        CSDLDataContext db = new CSDLDataContext();
        public ActionResult Index()
        {
            List<AllNXBResult> lstnxb = db.AllNXB().ToList();
            return View(lstnxb);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(NhaXuatBan nxb)
        {
            db.AddNXB(nxb.MaNXB,nxb.TenNXB,nxb.Email,nxb.SDT,nxb.DiaChi);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            NhaXuatBan nxb = db.NhaXuatBans.FirstOrDefault(x => x.IDNXB == id);
            if (nxb != null)
            {
                db.DeleteNXB(id);
            }
            return RedirectToAction("Index");
        }

        //public ActionResult Edit(int id)
        //{
        //    var data = db.NhanViens.FirstOrDefault(x => x.IDNhanVien == id);
        //    return View(data);
        //}

        public ActionResult Edit(int id)
        {
            Get_NXB_forIDResult nxb = db.Get_NXB_forID(id).FirstOrDefault();
            if (Request.Form.Count > 0)
            {
                string MaNXB = Request.Form["MaNXB"];
                string TenNXB = Request.Form["TenNXB"];
                string Email = Request.Form["Email"];
                string SDT = Request.Form["SDT"];
                string DiaChi = Request.Form["DiaChi"];
                db.EditNXB(nxb.IDNXB, MaNXB, TenNXB, Email,SDT,DiaChi);
                db.SubmitChanges();
                TempData["AlertMessage"] = " Cập nhật thành công";
                return RedirectToAction("Index");
            }

            return View(nxb);
        }
    }
}

CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Views/NhaXuatBan/Create.cshtml
@model CuaHangSachOnline.Models.NhaXuatBan

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/PageManagement/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản Nhà Xuất Bản</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Index">Home</a></li>
                    <li class="breadcrumb-item active">Trang Quản Lý</li>
                    <li class="breadcrumb-item active">Quản Nhà Xuất Bản</li>
                    <li class="breadcrumb-item active">Thêm Nhà Xuất Bản</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Thêm Nhà Xuất Bản</h3>
                    </div>
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label("Mã NXB", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.MaNXB, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MaNXB, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Tên NXB", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TenNXB, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TenNXB, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("SDT", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("DiaChi", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Views/NhaXuatBan/Edit.cshtml
@model CuaHangSachOnline.Models.Get_NXB_forIDResult

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/PageManagement/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản Nhà Xuất Bản</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Index">Home</a></li>
                    <li class="breadcrumb-item active">Trang Quản Lý</li>
                    <li class="breadcrumb-item active">Quản Nhà Xuất Bản</li>
                    <li class="breadcrumb-item active">Sửa Nhà Xuất Bản</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Sửa Nhà Xuất Bản</h3>
                    </div>
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.IDNXB)

                        <div class="form-group">
                            @Html.Label("Mã NXB", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.MaNXB, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MaNXB, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Tên NXB", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TenNXB, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TenNXB, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("SDT", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("DiaChi", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Views/NhaXuatBan/Index.cshtml
@model IEnumerable<CuaHangSachOnline.Models.AllNXBResult>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/PageManagement/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"> Quản Lý Nhà Xuất Bản</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Index">Home</a></li>
                    <li class="breadcrumb-item active">Trang Quản Lý</li>
                    <li class="breadcrumb-item active">Quản Lý Nhà Xuất Bản</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <button type="button" onclick="location.href='@Url.Action("Create", "NhaXuatBan")'" class="btn btn-success btn-sm">Thêm Mới</button>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <table class="table table-hover text-nowrap">
                <tr>
                    <th>
                        Mã NXB
                    </th>
                    <th>
                        Tên NXB
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        SDT
                    </th>
                    <th>
                        Địa Chỉ
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaNXB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenNXB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SDT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DiaChi)
                        </td>
                        <td>
                            @Html.ActionLink("Sửa", "Edit", new { id=item.IDNXB }) |
                            @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                            @Html.ActionLink("Xóa", "Delete", new { id=item.IDNXB})
                        </td>
                    </tr>
                }

            </table>
            </div>
</div>
</div>