CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Controllers/NganHangController.cs
using CuaHangSachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSachOnline.Areas.PageManagement.Controllers
{
    public class NganHangController : Controller
    {
        // GET: PageManagement/NganHang
        CSDLDataContext db = new CSDLDataContext();
        public ActionResult Index()
        {
            List<AllNganHangResult> lstnh = db.AllNganHang().ToList();
            return View(lstnh);
        }

        public ActionResult Create()
        {
            TempData["AllHTTT"] = db.AllHTTT().ToList();
            return View();
        }


        [HttpPost]
        public ActionResult Create(NganHang nh)
        {

            db.AddNganHang(nh.MaNganHang, nh.TenNganHang,Convert.ToInt32(nh.HinhThucThanhToanIDHTTT));
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            NganHang nh = db.NganHangs.FirstOrDefault(x => x.IDNganHang == id);
            if (nh != null)
            {
                db.DeleteNH(id);
            }
            return RedirectToAction("Index");
        }

        //public ActionResult Edit(int id)
        //{
        //    var data = db.NhanViens.FirstOrDefault(x => x.IDNhanVien == id);
        //    return View(data);
        //}

        public ActionResult Edit(int id)
        {
            Get_NH_forIDResult nh = db.Get_NH_forID(id).FirstOrDefault();
            TempData["AllHTTT"] = db.AllHTTT().ToList();
            if (Request.Form.Count > 0)
            {
                string MaNganHang = Request.Form["MaNganHang"];
                string TenNganHang = Request.Form["TenNganHang"];
                int HinhThucThanhToanIDHTTT = Convert.ToInt32(Request.Form["HinhThucThanhToanIDHTTT"]);
                db.EditNganHang(nh.IDNganHang,MaNganHang, TenNganHang, HinhThucThanhToanIDHTTT);
                db.SubmitChanges();
                TempData["AlertMessage"] = " Cập nhật thành công";
                return RedirectToAction("Index");
            }

            return View(nh);
        }
    }
}

CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Views/NganHang/Create.cshtml
@model CuaHangSachOnline.Models.NganHang
@using CuaHangSachOnline.Models
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/PageManagement/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản Lý Ngân Hàng</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Index">Home</a></li>
                    <li class="breadcrumb-item active">Trang Quản Lý</li>
                    <li class="breadcrumb-item active">Quản Lý Ngân Hàng</li>
                    <li class="breadcrumb-item active">Thêm Ngân Hàng</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Thêm Ngân Hàng</h3>
                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Mã Ngân Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MaNganHang, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MaNganHang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Tên Ngân Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenNganHang, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenNganHang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Hình Thức Thanh Toán", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="HinhThucThanhToanIDHTTT" style="outline:none" class="form-control">
                                @foreach (var item in TempData["AllHTTT"] as List<AllHTTTResult>)
                                {
                                    <option value="@item.IDHTTT">
                                        @item.TenHTTT
                                    </option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Views/NganHang/Edit.cshtml
@model CuaHangSachOnline.Models.Get_NH_forIDResult
@using CuaHangSachOnline.Models

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/PageManagement/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản Lý Ngân Hàng</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Index">Home</a></li>
                    <li class="breadcrumb-item active">Trang Quản Lý</li>
                    <li class="breadcrumb-item active">Quản Lý Ngân Hàng</li>
                    <li class="breadcrumb-item active">Sửa Ngân Hàng</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Sửa Ngân Hàng</h3>
                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">

                    <div class="form-group">
                        @Html.Label("Mã Ngân Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MaNganHang, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MaNganHang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Tên Ngân Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenNganHang, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenNganHang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Hình Thức Thanh Toán", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="HinhThucThanhToanIDHTTT" style="outline:none" class="form-control">
                                @foreach (var item in TempData["AllHTTT"] as List<AllHTTTResult>)
                                {
                                    <option value="@item.IDHTTT">
                                        @item.TenHTTT
                                    </option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

CuaHangSachOnline/CuaHangSachOnline/Areas/PageManagement/Views/NganHang/Index.cshtml
@model IEnumerable<CuaHangSachOnline.Models.AllNganHangResult>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/PageManagement/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"> Quản Lý Ngân Hàng </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Index">Home</a></li>
                    <li class="breadcrumb-item active">Trang Quản Lý</li>
                    <li class="breadcrumb-item active">Quản Lý Ngân Hàng</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <button type="button" onclick="location.href='@Url.Action("Create", "NganHang")'" class="btn btn-success btn-sm">Thêm Mới</button>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <table class="table table-hover text-nowrap">
                <tr>
                    <th>
                        Mã Ngân Hàng
                    </th>
                    <th>
                       Tên Ngân Hàng
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaNganHang)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenNganHang)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.IDNganHang }) |
                            @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                            @Html.ActionLink("Delete", "Delete", new { id=item.IDNganHang})
                        </td>
                    </tr>
                }
                

            </table>
            </div>
        </div>
    </div>