CuaHangSachOnline/CuaHangSachOnline/Controllers/DanhMucSachController.cs
using CuaHangSachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSachOnline.Controllers
{
    public class DanhMucSachController : Controller
    {
        CSDLDataContext db = new CSDLDataContext();
        // GET: DanhMucSach
        public ActionResult Index()
        {
            List<LoaiSach> lstLoaiSach = db.LoaiSaches.ToList();
            return View(lstLoaiSach);
        }

        public ActionResult DanhSachtheoLoaiSach(int id)
        {
            List<DanhSachtheoLoaiSachResult> lstSachtheoLoaiSach = db.DanhSachtheoLoaiSach(id).ToList();
            return View(lstSachtheoLoaiSach);
        }
    }
}

CuaHangSachOnline/CuaHangSachOnline/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuaHangSachOnline.Models;

namespace CuaHangSachOnline.Controllers
{
    public class HomeController : Controller
    {

        CSDLDataContext db = new CSDLDataContext();

        public ActionResult Index()
        {
            
            HomeModel objhomeModel = new HomeModel();
            objhomeModel.lstLoaiSach = db.LoaiSaches.ToList();
            objhomeModel.lstSach = db.Saches.ToList();
            return View(objhomeModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [ChildActionOnly]
        public ActionResult RenderMenu()
        {
            var dsLoaiSach = db.LoaiSaches.ToList();
            ViewBag.dsls = dsLoaiSach;
            return PartialView("_MenuHeader");
        }



    }
}

CuaHangSachOnline/CuaHangSachOnline/Controllers/SachController.cs
using CuaHangSachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSachOnline.Controllers
{
    public class SachController : Controller
    {
        CSDLDataContext db = new CSDLDataContext();
        // GET: Sach
        public ActionResult ThongTinSachMua(int id)
        {
            ChiTietSachBanResult ttsb = db.ChiTietSachBan(id).FirstOrDefault();
            return View(ttsb);
        }

        public ActionResult ThongTinSachThue(int id)
        {

            ChiTietSachThueResult ttst = db.ChiTietSachThue(id).FirstOrDefault();
            return View(ttst);
        }

    }
}

CuaHangSachOnline/CuaHangSachOnline/Views/Home/About.cshtml
@model IEnumerable<CuaHangSachOnline.Models.Sach>

@{
    ViewBag.Title = "About";
}

<h2>About</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NamXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TaiBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaThue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Metakeyword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.File_PDF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MucLuc_PDF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiSachIDLoaiSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhaXuatBanIDNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgonNguIDNgonNgu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ViTriIDViTri)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrangThai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TacGiaIDTacGia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NamXB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TaiBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaThue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Metakeyword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MetaDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.File_PDF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MucLuc_PDF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.active)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.LoaiSachIDLoaiSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaXuatBanIDNXB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgonNguIDNgonNgu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ViTriIDViTri)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrangThai)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TacGiaIDTacGia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDSach }) |
            @Html.ActionLink("Details", "Details", new { id=item.IDSach }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IDSach })
        </td>
    </tr>
}

</table>

CuaHangSachOnline/CuaHangSachOnline/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CuaHangSachOnline/CuaHangSachOnline/Views/Home/Index.cshtml
@model CuaHangSachOnline.Models.HomeModel

@{
    ViewBag.Title = "Home Page";
}

@{
    Html.RenderAction("RenderMenu", "Home");
}

<div class="container">
    <!-- ========================= SECTION MAIN  ========================= -->
    <section class="section-main padding-y">
        <main class="card">
            <div class="card-body">

                <div class="row">
                    <aside class="col-lg col-md-3 flex-lg-grow-0">
                        <h6>Loại Sách</h6>
                        <nav class="nav-home-aside">
                            <ul class="menu-category">

                                @foreach (var item in Model.lstLoaiSach)
                                {
                                    <li>
                                        @Html.ActionLink(item.TenLoaiSach, "DanhSachtheoLoaiSach", "DanhMucSach", new { @id = item.IDLoaiSach}, null)
                                    </li>
                                }

                            </ul>
                        </nav>
                    </aside> <!-- col.// -->
                    <div class="col-md-9 col-xl-7 col-lg-7">

                        <!-- ================== COMPONENT SLIDER  BOOTSTRAP  ==================  -->
                        <div id="carousel1_indicator" class="slider-home-banner carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel1_indicator" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel1_indicator" data-slide-to="1"></li>
                                <li data-target="#carousel1_indicator" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img src="~/Content/images/banners/0x300a0a0.jpg" alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img src="~/Content/images/banners/slide13.jpg" alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img src="~/Content/images/banners/slide456.jpg" alt="Third slide">
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#carousel1_indicator" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel1_indicator" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!-- ==================  COMPONENT SLIDER BOOTSTRAP end.// ==================  .// -->

                    </div> <!-- col.// -->
                    <div class="col-md d-none d-lg-block flex-grow-1">
                        <aside class="special-home-right">
                            <h6 class="bg-blue text-center text-white mb-0 p-2">Loại Sách Phổ Biến</h6>

                            @foreach (var item in Model.lstLoaiSach.Where(n => n.TrangThai == "hot").Take(3))
                            {
                                <div class="card-banner border-bottom">
                                    <div class="py-3" style="width:80%">
                                        <h6 class="card-title">@item.TenLoaiSach</h6>
                                        <a href="@Url.Action("DanhSachtheoLoaiSach", "DanhMucSach", new { @id = item.IDLoaiSach})" class="btn btn-secondary btn-sm">Xem</a>
                                    </div>
                                    <img src="~/Content/images/@item.Imagels" height="80" class="img-bg">
                                </div>
                            }

                        </aside>
                    </div> <!-- col.// -->
                </div> <!-- row.// -->

            </div> <!-- card-body.// -->
        </main> <!-- card.// -->

    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->
    <!-- =============== SECTION DEAL =============== -->
    <!-- =============== SECTION DEAL // END =============== -->
    <!-- =============== SECTION 1 =============== -->
    <!-- =============== SECTION 1 END =============== -->
    <!-- =============== SECTION 2 =============== -->
    <!-- =============== SECTION 2 END =============== -->
    <!-- =============== SECTION REQUEST =============== -->
    <!-- =============== SECTION REQUEST .//END =============== -->
    <!-- =============== SECTION ITEMS =============== -->
    <section class="padding-bottom-sm">

        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Sách Thuê Mới</h4>
        </header>

        <div class="row row-sm">
            @foreach (var item in Model.lstSach.Where(n => n.TrangThai == "new" && n.LoaiSachXem == "rental").Take(10))
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div href="@Url.Action("ThongTinSachThue", "Sach", new {id = item.IDSach})" class="card card-sm card-product-grid">
                        <a href="@Url.Action("ThongTinSachThue", "Sach", new {id = item.IDSach})" class="img-wrap"> <img src="~/Content/images/@item.Image"> </a>
                        <figcaption class="info-wrap">
                            <a href="@Url.Action("ThongTinSachThue", "Sach", new {id = item.IDSach})" class="title">@item.TenSach</a>
                            <div class="price mt-1">@string.Format("{0:#,0}", @item.GiaThue)VND</div> <!-- price-wrap.// -->
                        </figcaption>
                    </div>
                </div> <!-- col.// -->
            }
        </div> <!-- row.// -->
    </section>
    <!-- =============== SECTION ITEMS .//END =============== -->
    <!-- =============== SECTION ITEMS =============== -->
    <section class="padding-bottom-sm">

        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Sách Mua Mới</h4>
        </header>

        <div class="row row-sm">
            @foreach (var item in Model.lstSach.Where(n => n.TrangThai == "new" && n.LoaiSachXem == "buy").Take(10))
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div href="@Url.Action("ThongTinSachMua", "Sach", new {id = item.IDSach})" class="card card-sm card-product-grid">
                        <a href="@Url.Action("ThongTinSachMua", "Sach", new {id = item.IDSach})" class="img-wrap"> <img src="~/Content/images/@item.Image"> </a>    @*~/Content/images/items/1.jpg*@
                        <figcaption class="info-wrap">
                            <a href="@Url.Action("ThongTinSachMua", "Sach", new {id = item.IDSach})" class="title">@item.TenSach</a>
                            <div class="price mt-1">@string.Format("{0:#,0}", @item.GiaBan)VND</div> <!-- price-wrap.// -->
                        </figcaption>
                    </div>
                </div> <!-- col.// -->
            }


        </div> <!-- row.// -->
    </section>
    <!-- =============== SECTION ITEMS .//END =============== -->
    <!-- =============== SECTION SERVICES =============== -->
    <section class="padding-bottom">

        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Trade services</h4>
        </header>

        <div class="row">
            <div class="col-md-3 col-sm-6">
                <article class="card card-post">
                    <img src="~/Content/images/posts/1.jpg" class="card-img-top">
                    <div class="card-body">
                        <h6 class="title">Trade Assurance</h6>
                        <p class="small text-uppercase text-muted">Order protection</p>
                    </div>
                </article> <!-- card.// -->
            </div> <!-- col.// -->
            <div class="col-md-3 col-sm-6">
                <article class="card card-post">
                    <img src="~/Content/images/posts/2.jpg" class="card-img-top">
                    <div class="card-body">
                        <h6 class="title">Pay anytime</h6>
                        <p class="small text-uppercase text-muted">Finance solution</p>
                    </div>
                </article> <!-- card.// -->
            </div> <!-- col.// -->
            <div class="col-md-3 col-sm-6">
                <article class="card card-post">
                    <img src="~/Content/images/posts/3.jpg" class="card-img-top">
                    <div class="card-body">
                        <h6 class="title">Inspection solution</h6>
                        <p class="small text-uppercase text-muted">Easy Inspection</p>
                    </div>
                </article> <!-- card.// -->
            </div> <!-- col.// -->
            <div class="col-md-3 col-sm-6">
                <article class="card card-post">
                    <img src="~/Content/images/posts/4.jpg" class="card-img-top">
                    <div class="card-body">
                        <h6 class="title">Ocean and Air Shipping</h6>
                        <p class="small text-uppercase text-muted">Logistic services</p>
                    </div>
                </article> <!-- card.// -->
            </div> <!-- col.// -->
        </div> <!-- row.// -->

    </section>
    <!-- =============== SECTION SERVICES .//END =============== -->
    <!-- =============== SECTION REGION =============== -->
    <!-- =============== SECTION REGION .//END =============== -->

    <article class="my-4">
        <img src="~/Content/images/banners/ad-sm.png" class="w-100">
    </article>
</div>


<!-- container end.// -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->